# Generated by Django 4.1.7 on 2023-04-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0008_remove_techniciandetails_tech_sched_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='technicianschedule',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_scheds', to='JohnCarAirCo.techniciandetails'),
        ),
        migrations.CreateModel(
            name='SupplyOrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='JohnCarAirCo.supplyorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JohnCarAirCo.productunit')),
            ],
        ),
    ]
